<?php

namespace CodeShopping\Http\Filters;

use Illuminate\Database\Eloquent\Builder;
use Mnabialek\LaravelEloquentFilter\Filters\SimpleQueryFilter;

class ProductInputFilter extends SimpleQueryFilter
{
    protected $simpleFilters = ['search'];

    protected $simpleSorts = ['id','product_name','amount','created_at'];

    protected function applySearch($value){
        $this->query->where('name','LIKE', "%${value}%");
    }

    protected function applySortProductName($order){
        $this->query->orderBy('products.name',$order);
    }

    protected function applySortCreatedAt($order){
        $this->query->orderBy('product_inputs.created_at',$order);
    }

    /**
     * @param Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply($query)
    {
        $query = $query->join('products','products.id','=','product_inputs.product_id')
            ->select('product_inputs.*');

        return parent::apply($query); // TODO: Change the autogenerated stub
    }
}